import swapper
from django.db import transaction
from django.utils.translation import gettext_lazy as _
from dynamicforms import fields
from dynamicforms.mixins import DisplayMode
from dynamicforms.serializers import ModelSerializer
from dynamicforms.viewsets import ModelViewSet
from rest_framework.permissions import IsAuthenticated

from django_project_base.account.middleware import ProjectNotSelectedError
from django_project_base.base.exceptions import InviteActionNotImplementedException


class ProjectUserInviteSerializer(ModelSerializer):
    template_context = dict(url_reverse="project-user-invite")
    form_titles = {
        "table": "",
        "new": _("Inviting project member"),
        "edit": "",
    }

    accepted = fields.AutoGeneratedField(display=DisplayMode.HIDDEN)
    send_by = fields.AutoGeneratedField(display=DisplayMode.HIDDEN)
    project = fields.PrimaryKeyRelatedField(
        display=DisplayMode.SUPPRESS,
        queryset=swapper.load_model("django_project_base", "Project").objects.all(),
    )

    # def confirm_create_text(self):
    #     owner_change_data = get_owner_change_data(self.context)
    #     if owner_change_data:
    #         return change_owner_warning(owner_change_data.get("free_projects_number"))
    #     return False
    #
    # def confirm_create_title(self):
    #     return _("Create project user invite confirmation")

    # def create(self, validated_data):
    # languages = validated_data.pop("languages")
    # validated_data["send_by"] = self.context["request"].user
    # invite = ProjectUserInvite.objects.create(**validated_data)
    # invite.languages.set(languages)
    #
    # # send email/generate url
    # invite_url = (
    #     ("https" if not settings.DEBUG else "http")
    #     + "://"
    #     + self.context["request"].get_host()
    #     + reverse("signup")
    #     + "%sinvitation_id=%s" % ("/?", str(invite.guid))
    # )
    # user_invite_created.send(sender=ProjectUserInvite, user_invite=invite, user_invite_url=invite_url)

    # return super().create()

    class Meta:
        model = swapper.load_model("django_project_base", "Invite")
        exclude = ()


class ProjectUserInviteViewSet(ModelViewSet):
    permission_classes = (IsAuthenticated,)
    serializer_class = ProjectUserInviteSerializer

    def get_queryset(self):
        project = self.request.selected_project
        try:
            return swapper.load_model("django_project_base", "Invite").objects.filter(project_id=project)
        except ProjectNotSelectedError:
            return swapper.load_model("django_project_base", "ProjectMember").objects.none()

    def new_object(self: ModelViewSet):
        new_object = super().new_object()
        if project := self.request.selected_project:
            new_object.project = project
        return new_object

    def retrieve(self: ModelViewSet, request, *args, **kwargs):
        return super().retrieve(request, *args, **kwargs)

    @transaction.atomic
    def create(self, request, *args, **kwargs):
        self.request.data["project"] = self.request.selected_project
        self.request.data["send_by"] = self.request.user.userprofile
        return super().create(request, *args, **kwargs)

    @transaction.atomic
    def update(self, request, *args, **kwargs):
        raise InviteActionNotImplementedException

    @transaction.atomic
    def partial_update(self, request, *args, **kwargs):
        raise InviteActionNotImplementedException

    @transaction.atomic
    def destroy(self, request, *args, **kwargs):
        raise InviteActionNotImplementedException

    def list(self, request, *args, **kwargs):
        return super().list(request, *args, **kwargs)
