# Generated by Django 3.1.5 on 2021-02-10 07:40
import copy

from django.contrib.auth.hashers import make_password
from django.db import migrations

from django_project_base.settings import TEST_USER_ONE_DATA, TEST_USER_TWO_DATA


class Migration(migrations.Migration):
    dependencies = [
        ('demo_django_base', '0001_initial'),
    ]

    def forwards_func(apps, schema_editor):
        ProjectModel = apps.get_model("demo_django_base", "Project")
        UserProfileModel = apps.get_model("demo_django_base", "UserProfile")
        db_alias = schema_editor.connection.alias
        user_one_data: dict = copy.copy(TEST_USER_ONE_DATA)
        user_two_data: dict = copy.copy(TEST_USER_TWO_DATA)
        user_one_data.update(dict(password=make_password(TEST_USER_ONE_DATA['password'])))
        user_two_data.update(dict(password=make_password(TEST_USER_TWO_DATA['password'])))
        user1 = UserProfileModel.objects.using(db_alias).create(**user_one_data)
        user2 = UserProfileModel.objects.using(db_alias).create(**user_two_data)
        ProjectModel.objects.using(db_alias).bulk_create([
            ProjectModel(name='Project One', slug='project-one', description='project one description',
                         owner=user1),
            ProjectModel(name='Project Two', slug='project-two', description='project two description',
                         owner=user2),
            ProjectModel(name='Project Three', slug='project-three', description='project three description',
                         owner=user2),
            ProjectModel(name='Project Four', slug='project-four', description='project four description',
                         owner=user1),
        ])

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
