# Generated by Django 3.1.5 on 2021-02-10 07:40
from django.contrib.auth.hashers import make_password
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('demo_django_base', '0001_initial'),
    ]

    def forwards_func(apps, schema_editor):
        ProjectModel = apps.get_model("demo_django_base", "Project")
        UserProfileModel = apps.get_model("demo_django_base", "UserProfile")
        db_alias = schema_editor.connection.alias

        user1 = UserProfileModel.objects.using(db_alias).create(username='miha', last_name='Novak',
                                                                first_name='Miha',
                                                                email='user1@user1.si',
                                                                password=make_password('mihamiha'))
        user2 = UserProfileModel.objects.using(db_alias).create(username='janez', last_name='Novak',
                                                                first_name='Janez',
                                                                email='user2@user2.si',
                                                                password=make_password('janezjanez'))
        ProjectModel.objects.using(db_alias).bulk_create([
            ProjectModel(name='Project One', slug='project-one', description='project one description',
                         owner=user1),
            ProjectModel(name='Project Two', slug='project-two', description='project two description',
                         owner=user2),
            ProjectModel(name='Project Three', slug='project-three', description='project three description',
                         owner=user2),
            ProjectModel(name='Project Four', slug='project-four', description='project four description',
                         owner=user1),
        ])

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
