# Generated by Django 3.1.5 on 2021-02-15 06:49

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    apps.get_model("demo_django_base", "Project").objects.all().update(logo='https://via.placeholder.com/500')


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('demo_django_base', '0002_auto_20210210_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.CharField(default='https://via.placeholder.com/500', max_length=256),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
