# Generated by Django 3.1.5 on 2021-02-16 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_project_base.base.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('demo_django_base', '0003_auto_20210215_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoProjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('color', django_project_base.base.fields.HexColorField(max_length=7)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('content', models.CharField(blank=True, max_length=20, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.DJANGO_PROJECT_BASE_PROJECT_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='TaggedItemThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_django_base_taggeditemthrough_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_django_base_taggeditemthrough_items', to='demo_django_base.demoprojecttag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='apartment_tags', through='demo_django_base.TaggedItemThrough', to='demo_django_base.DemoProjectTag', verbose_name='Tags')),
            ],
        ),
    ]
