# Generated by Django 3.1.10 on 2021-05-20 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_project_base.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo_django_base', '0005_auto_20210325_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoprojecttag',
            name='color',
            field=django_project_base.base.fields.HexColorField(max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='demoprojecttag',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='demoprojecttag',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.DJANGO_PROJECT_BASE_PROJECT_MODEL, verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=80, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=80, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Theme'),
        ),
    ]
