# Generated by Django 4.2.4 on 2023-10-02 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demo_django_base", "0007_merge_20230927_0554"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectInvite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255, verbose_name="eMail")),
                ("accepted", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.DJANGO_PROJECT_BASE_PROJECT_MODEL,
                    ),
                ),
                (
                    "send_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_user_invites",
                        to=settings.DJANGO_PROJECT_BASE_PROFILE_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
