# Generated by Django 3.1.11 on 2021-06-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_django_base', '0007_userprofile_reverse_full_name_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delete profile at'),
        ),
    ]
