# Generated by Django 4.2.4 on 2023-10-02 13:05
from gettext import gettext

import swapper
from django.db import migrations, models

from django_project_base.constants import INVITE_NOTIFICATION_TEXT


def forwards_func(apps, schema_editor):
    project_sett = swapper.load_model("django_project_base", "ProjectSettings")
    for project in swapper.load_model("django_project_base", "Project").objects.all():
        project_sett.objects.create(
            project=project,
            name=INVITE_NOTIFICATION_TEXT,
            description="Text for invite notification view. __LINK__ is url to invite confirmation placeholder.",
            value=gettext("Click link to join project: __LINK__"),
            value_type="char",
        )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("demo_django_base", "0008_projectinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectinvite",
            name="host_url",
            field=models.CharField(max_length=1024, null=False, blank=False),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
