# Generated by Django 4.2.4 on 2023-10-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo_django_base", "0008_projectinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="pending_value",
            field=models.CharField(
                max_length=320, null=True, verbose_name="Pending value"
            ),
        ),
    ]
