# Generated by Django 3.1 on 2023-06-07 06:54

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        ("demo_django_base", "0010_userprofile_admin_password_reset"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergeUserGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "users",
                    models.CharField(
                        max_length=1024,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^\\d+(?:,\\d+)*\\Z"),
                                code="invalid",
                                message="Enter only digits separated by commas.",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="mergeusergroup",
            name="created_by",
            field=models.PositiveIntegerField(),
        ),
    ]
