# Generated by Django 4.2.1 on 2023-06-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_django_base', '0012_alter_taggeditemthrough_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoprojecttag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
