# Generated by Django 3.1.14 on 2023-07-14 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_django_base', '0013_alter_demoprojecttag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergeusergroup',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='demo_django_base.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demoprojecttag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
