# Generated by Django 3.1.14 on 2023-07-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_django_base', '0015_alter_demoprojecttag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoprojecttag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
