# Generated by Django 3.1.5 on 2021-02-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangoprojectbasenotification',
            old_name='channels',
            new_name='required_channels',
        ),
        migrations.AddField(
            model_name='djangoprojectbasenotification',
            name='delayed_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djangoprojectbasenotification',
            name='sent_channels',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
