# Generated by Django 3.1.11 on 2021-05-27 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_project_base.notifications.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoprojectbasemessage',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasemessage',
            name='footer',
            field=models.TextField(blank=True, null=True, verbose_name='Footer'),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasemessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasemessage',
            name='subject',
            field=models.TextField(blank=True, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='created_at',
            field=models.DateTimeField(default=django_project_base.notifications.utils.utc_now, editable=False, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='delayed_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delayed to'),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='failed_channels',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Failed channels'),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='level',
            field=models.CharField(choices=[('success', 'Success'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=16, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='locale',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.djangoprojectbasemessage', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipients'),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='required_channels',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Required channels'),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent at'),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='sent_channels',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Sent channels'),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='type',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('standard', 'Standard')], default='standard', max_length=16, verbose_name='Type'),
        ),
    ]
