# Generated by Django 4.2.4 on 2023-08-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="djangoprojectbasenotification",
            name="project",
        ),
        migrations.AddField(
            model_name="djangoprojectbasenotification",
            name="project_slug",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
