# Generated by Django 3.1.5 on 2021-02-25 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_auto_20210225_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoprojectbasenotification',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='djangoprojectbasenotification',
            name='type',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('standard', 'Standard')], default='standard', max_length=16),
        ),
    ]
