# Generated by Django 4.2.2 on 2023-06-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_auto_20210527_1155"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangoprojectbasemessage",
            name="content_type",
            field=models.CharField(
                choices=[("text/plain", "Plain text"), ("text/html", "Html")],
                default="text/plain",
                max_length=64,
            ),
        ),
    ]
