# Generated by Django 3.1.14 on 2023-07-14 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_djangoprojectbasemessage_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoprojectbasenotification',
            name='recipients',
        ),
        migrations.AddField(
            model_name='djangoprojectbasenotification',
            name='recipients',
            field=models.CharField(max_length=2048, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
