# Generated by Django 3.1.5 on 2021-02-25 12:30

from django.db import migrations, models
import django_project_base.notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210225_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='created_at',
            field=models.DateTimeField(default=django_project_base.notifications.models._utc_now, editable=False),
        ),
    ]
