# Generated by Django 4.2.4 on 2023-09-05 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_djangoprojectbasemessage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="djangoprojectbasenotification",
            options={"verbose_name": "Notification"},
        ),
    ]
