# Generated by Django 3.1.5 on 2021-03-29 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_auto_20210225_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='recipients',
            field=models.ManyToManyField(blank=True, null=True, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
