# Generated by Django 4.2.4 on 2023-09-06 12:13

from django.db import migrations

from django_project_base.notifications.base.channels.integrations.t2 import T2


def forwards_func(apps, schema_editor):
    ProjectModel = apps.get_model("demo_django_base", "Project")
    ProjectModelSettings = apps.get_model("demo_django_base", "ProjectSettings")
    t2 = T2()
    username = t2.delivery_report_username_setting_name
    passwd = t2.delivery_report_password_setting_name
    for project in ProjectModel.objects.all():
        ProjectModelSettings.objects.create(
            name=username,
            project=project,
            description="T2 username for DLR user",
            value="",
            value_type="char",
        )

        ProjectModelSettings.objects.create(
            name=passwd,
            project=project,
            description="T2 password for DLR user",
            value="",
            value_type="char",
        )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_alter_djangoprojectbasenotification_options"),
        ("notifications", "0004_alter_djangoprojectbasenotification_options_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
