# Generated by Django 3.1.5 on 2021-03-29 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0005_auto_20210329_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoProjectBaseMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, null=True)),
                ('body', models.TextField()),
                ('footer', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='djangoprojectbasenotification',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.djangoprojectbasemessage'),
        ),
    ]
