# Generated by Django 3.1.14 on 2023-07-21 13:17
import uuid

from django.db import migrations, models
import django_project_base.notifications.utils


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_djangoprojectbasenotification_exceptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangoprojectbasenotification",
            name="content_entity_context",
            field=models.TextField(default=lambda: str(uuid.uuid4())),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="djangoprojectbasenotification",
            name="counter",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="djangoprojectbasenotification",
            name="created_at",
        ),
        migrations.AddField(
            model_name="djangoprojectbasenotification",
            name="created_at",
            field=models.BigIntegerField(editable=False, default=0, verbose_name="Created at"),
        ),
        migrations.RemoveField(
            model_name="djangoprojectbasenotification",
            name="delayed_to",
        ),
        migrations.AddField(
            model_name="djangoprojectbasenotification",
            name="delayed_to",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Sent at"),
        ),
        migrations.RemoveField(
            model_name="djangoprojectbasenotification",
            name="sent_at",
        ),
        migrations.AddField(
            model_name="djangoprojectbasenotification",
            name="sent_at",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Sent at"),
        ),
    ]
