# Generated by Django 3.1.14 on 2023-07-25 14:21

from django.db import migrations, models
import django_project_base.notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20230721_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='counter',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='djangoprojectbasenotification',
            name='created_at',
            field=models.BigIntegerField(default=django_project_base.notifications.models.integer_ts, editable=False, verbose_name='Created at'),
        ),
    ]
