# Generated by Django 3.1.5 on 2021-03-29 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20210329_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoprojectbasemessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
