# Generated by Django 3.1.14 on 2023-08-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20230807_0811'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='searchitems',
            table='search-items-table',
        ),
    ]
