# Generated by Django 3.1.14 on 2023-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20230807_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoprojectbasenotification',
            name='recipients_original_payload',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
