# Generated by Django 3.1.14 on 2023-08-11 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.DJANGO_PROJECT_BASE_PROJECT_MODEL),
        ("notifications", "0010_djangoprojectbasenotification_recipients_original_payload"),
    ]

    operations = []
