# Generated by Django 4.2.4 on 2023-11-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0010_djangoprojectbasenotification_send_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangoprojectbasenotification",
            name="extra_data",
            field=models.JSONField(null=True),
        ),
    ]
