# Generated by Django 3.1.14 on 2023-08-11 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.DJANGO_PROJECT_BASE_PROJECT_MODEL),
        ("notifications", "0011_djangoprojectbasenotification_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangoprojectbasenotification",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.DJANGO_PROJECT_BASE_PROJECT_MODEL,
            ),
            preserve_default=False,
        ),
    ]
