# Generated by Django 4.2.4 on 2023-08-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0012_auto_20230811_1511"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangoprojectbasenotification",
            name="recipients_original_payload_search",
            field=models.TextField(db_index=True, null=True),
        ),
    ]
