# Generated by Django 4.2.4 on 2023-08-28 12:55

from django.db import migrations, models
import django_project_base.licensing.models


class Migration(migrations.Migration):
    dependencies = [
        ("licensing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenseaccessuse",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="licenseaccessuse",
            name="type",
            field=models.IntegerField(
                choices=[
                    (
                        django_project_base.licensing.models.LicenseAccessUse.UseType["USE"],
                        "Used access",
                    )
                ],
                default=django_project_base.licensing.models.LicenseAccessUse.UseType["USE"],
                verbose_name="Type",
            ),
        ),
    ]
