# Generated by Django 4.2.4 on 2023-08-29 07:23

from django.db import migrations, models
import django_project_base.licensing.models


class Migration(migrations.Migration):
    dependencies = [
        ("licensing", "0002_remove_licenseaccessuse_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenseaccessuse",
            name="comment",
            field=models.JSONField(null=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="licenseaccessuse",
            name="type",
            field=models.IntegerField(
                choices=[
                    (
                        django_project_base.licensing.models.LicenseAccessUse.UseType[
                            "USE"
                        ],
                        "Used access",
                    ),
                    (
                        django_project_base.licensing.models.LicenseAccessUse.UseType[
                            "ADMIN_USE"
                        ],
                        "Used access by admin",
                    ),
                ],
                default=django_project_base.licensing.models.LicenseAccessUse.UseType[
                    "USE"
                ],
                verbose_name="Type",
            ),
        ),
    ]
