# Generated by Django 4.2.1 on 2023-08-18 11:51

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_project_base.base.fields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.DJANGO_PROJECT_BASE_PROFILE_MODEL),
        migrations.swappable_dependency(settings.DJANGO_PROJECT_BASE_PROJECT_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.permission')),
            ],
            options={
                'swappable': 'DJANGO_PROJECT_BASE_PERMISSION_MODEL',
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Language')),
                ('theme', models.CharField(blank=True, max_length=10, null=True, verbose_name='Theme')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='', verbose_name='Avatar')),
                ('reverse_full_name_order', models.BooleanField(blank=True, null=True, verbose_name='Reverse full name order')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='Delete profile at')),
                ('password_invalid', models.BooleanField(default=False)),
            ],
            options={
                'swappable': 'DJANGO_PROJECT_BASE_PROFILE_MODEL',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
            ],
            options={
                'swappable': 'DJANGO_PROJECT_BASE_ROLE_MODEL',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('color', django_project_base.base.fields.HexColorField(max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, max_length=10, null=True, verbose_name='Icon')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.DJANGO_PROJECT_BASE_PROJECT_MODEL, verbose_name='Project')),
            ],
            options={
                'swappable': 'DJANGO_PROJECT_BASE_TAG_MODEL',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.DJANGO_PROJECT_BASE_PROFILE_MODEL, verbose_name='Owner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.DJANGO_PROJECT_BASE_PROJECT_MODEL, verbose_name='Project')),
            ],
            options={
                'swappable': 'DJANGO_PROJECT_BASE_PROJECTMEMBER_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, verbose_name='Name')),
                ('slug', models.SlugField(max_length=80, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.DJANGO_PROJECT_BASE_PROFILE_MODEL, verbose_name='Owner')),
            ],
            options={
                'swappable': 'DJANGO_PROJECT_BASE_PROJECT_MODEL',
            },
        ),
        migrations.CreateModel(
            name='MergeUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('created_by', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.DJANGO_PROJECT_BASE_PROJECT_MODEL)),
            ],
            options={
                'swappable': 'DJANGO_PROJECT_BASE_MERGEUSERGROUP_MODEL',
            },
        ),
    ]
