from datetime import timedelta

INTERNAL_EMAIL_RENDER_QUERYSET_SIZE: int = 30
MAIL_AGGREGATION_TIMEDELTA: timedelta = timedelta(minutes=4)
INTERNAL_MAIL_LENGTH_SIMILARITY_BUFFER_VALUE: int = 3
INTERNAL_MAIL_CHECKING_REPORT_INTERVALS_IN_MINUTES: list = [30, 120, 480]
WAIT_MINUTES_AFTER_CREATED_MAIL_BEFORE_RETRYING_SEND: int = 2
