name: Black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Black
        continue-on-error: true
        uses: psf/black@stable
        with:
          options: '--check --line-length=120"'
