name: Coverage check
on: [push, pull_request]
jobs:
  lint:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: PIP install
        run: |
          pip3 install -r requirements.txt
          pip3 install coverage django_coverage_plugin
      - name: Python unittest
        continue-on-error: true
        run: |
          coverage run -m manage.py test
      - name: Generate coverage report
        continue-on-error: true
        run: |
          coverage report -m
          coverage json

      - name: Coverage check on pull_request
        uses: velis74/incremental-coverage-check@main
        with:
          py_coverage_json: coverage.json
          base_ref: ${{ github.base_ref }}
          head_ref: HEAD
          rep_ref: main
          logging_level: INFO
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{github.event.pull_request.number}}
        if: github.event_name == 'pull_request'

      - name: Coverage check on push
        uses: velis74/incremental-coverage-check@main
        with:
          py_coverage_json: coverage.json
          base_ref: ${{ github.event.before }}
          head_ref: HEAD
          rep_ref: main
          logging_level: INFO
          gh_token: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'push'
